server:
  port: 8086
  
  
spring:
  h2:
   console:
     enabled: true
     
keycloak:
  realm: quizapp
  auth-server-url: http://localhost:8080/auth
  resource: springboot-keycloak
  
  public-client: true
  bearer-only: true